/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "requests.h"
#include <math.h>

static InfoAuto *availableCars = NULL;
static InfoAuto  result;
int lengthBD = 0;

void *
updateCar(Data *argp){

	printf(
		"Termina viaje en x = %d, y = %d\n", 
		argp->posicion_final.x,
		argp->posicion_final.y
	);
	for (int i = 0; i < lengthBD; i++){
		if(!strcmp(argp->placa, availableCars[i].placa)){
			printf(
				"Lo encontré\n placaBuscada: %s placaEncontrada: %s\n",
				argp->placa,
				availableCars[i].placa
			);
			availableCars[i].posicion_pasajero.x = argp->posicion_final.x;
			availableCars[i].posicion_pasajero.y = argp->posicion_final.y;
			availableCars[i].status = 0;
			break;
		}
	}	
	printf("ACTUALIZACIÓN\n :");
	for(int j = 0; j < lengthBD; j++){
		printf("%s \n", availableCars[j].placa);
		printf("%d \n", availableCars[j].posicion_pasajero.x);
		printf("%d \n", availableCars[j].posicion_pasajero.y);
		printf("%s \n", availableCars[j].tipo);
		printf("%d \n", availableCars[j].status);
	}
}

void *
searchBestCar(int x, int y) 
{
	int countCarsAvailable = 0;
	double bestDistance = 1000000;
	int countBestCar = 0;
	
	for (int i = 0; i < lengthBD; i++){
		if (availableCars[i].status == 0){
			countCarsAvailable ++;
			double substractX = pow(availableCars[i].posicion_pasajero.x - x, 2);
			double substractY = pow(availableCars[i].posicion_pasajero.y - y, 2);
			double distanceNow = sqrt(substractX + substractY);
			printf("distanceNow %f \n", distanceNow);
			if (distanceNow < bestDistance){
				printf("BEST_DISTANCE %f \n", bestDistance);
				bestDistance = distanceNow;
				countBestCar = i;
			}
		}	
	}
	if(countCarsAvailable != 0){
		printf("Aún tenemos alguno disponible.\n");
		availableCars[countBestCar].status = 1;
		result.posicion_pasajero.x = availableCars[countBestCar].posicion_pasajero.x;
		result.posicion_pasajero.y = availableCars[countBestCar].posicion_pasajero.y;
		result.status = availableCars[countBestCar].status;
		result.tipo = (char*) malloc(sizeof(char)*30);
		result.placa = (char*) malloc(sizeof(char)*30);
		memcpy(result.tipo,availableCars[countBestCar].tipo,sizeof(char)*30);
		memcpy(result.placa,availableCars[countBestCar].placa,sizeof(char)*30);

	}else{
		/*Not Found Cars*/
		printf("Ups... Se nos acabaron los autos ):\n");
		result.placa = "";
		result.posicion_pasajero.x = -6;
		result.posicion_pasajero.y = -6;
		result.status = 404;
		result.tipo = "";
	}	
}

void *
loadDataBD() 
{
	FILE *file;
	file = fopen("BD.txt","r");
	fscanf(file,"%d",&lengthBD);
	availableCars = (InfoAuto*) malloc(sizeof(InfoAuto)*lengthBD);
	for(int i = 0; i < lengthBD; i++){
		fscanf(file,"%d",&availableCars[i].posicion_pasajero.x);
		fscanf(file,"%d",&availableCars[i].posicion_pasajero.y);
		fscanf(file,"%d",&availableCars[i].status);
		availableCars[i].tipo = (char*) malloc(sizeof(char)*10);
		fscanf(file,"%s",availableCars[i].tipo);
		availableCars[i].placa = (char*) malloc(sizeof(char)*10);
		fscanf(file,"%s",availableCars[i].placa);
	}
	fclose(file);
}

InfoAuto *
solicitarviaje_1_svc(Posicion *argp, struct svc_req *rqstp)
{
	printf("argp.x = %d\n", argp->x);
	printf("argp.y = %d\n", argp->y);
	if(availableCars == NULL){
		printf("Cargando data de BD...\n");
		loadDataBD();
	}
	searchBestCar(argp->x, argp->y);
	
	return (&result);
}

void *
terminarviaje_1_svc(Data *argp, struct svc_req *rqstp)
{
	static char * result;
	updateCar(argp);
	return (void *) &result;
}

