/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "requests.h"

bool_t
xdr_Posicion (XDR *xdrs, Posicion *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_InfoAuto (XDR *xdrs, InfoAuto *objp)
{
	register int32_t *buf;

	 if (!xdr_Posicion (xdrs, &objp->posicion_pasajero))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->tipo, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->placa, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Data (XDR *xdrs, Data *objp)
{
	register int32_t *buf;

	 if (!xdr_Posicion (xdrs, &objp->posicion_final))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->placa, ~0))
		 return FALSE;
	return TRUE;
}
