/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "requests.h"
#include<stdio.h>
#include<stdlib.h>
#include<time.h>
#include<unistd.h>

void
requests_1(char *host)
{
	CLIENT *clnt;
	InfoAuto  *result_1;
	Posicion  solicitarviaje_1_arg;
	void  *result_2;
	Data  terminarviaje_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, REQUESTS, SOLICITARVIAJEVERS1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	time_t t;
	srand((unsigned) time(&t));
	int x = rand() % 50;
	int y = rand() % 50;
	memcpy(
		&solicitarviaje_1_arg.x,
		&x,
		sizeof(int)*1
	);
	memcpy(
		&solicitarviaje_1_arg.y,
		&y,
		sizeof(int)*1
	);
	result_1 = solicitarviaje_1(&solicitarviaje_1_arg, clnt);
	if (result_1 == (InfoAuto *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	if(result_1->status == 404){
		printf("\nLo sentimos, no existen autos disponibles en este momento ):\n");
	}else{
		printf("\nBien! Te encontramos algo :D\n");
		printf(
			"Ubicación (La mejor en este momento :D) = x :%d y :%d\n", 
			result_1->posicion_pasajero.x,
			result_1->posicion_pasajero.y
		);		
		printf("Vas a viajar en un auto: %s. :O\n", result_1->tipo);
		printf("Guarda este dato para ti ;) => Placas: %s\n\n", result_1->placa);
	}
	printf("Comenzando tu viaje :)...\n");
	sleep(5);

	terminarviaje_1_arg.placa = result_1->placa;
	terminarviaje_1_arg.posicion_final.x = rand() % 50;
	terminarviaje_1_arg.posicion_final.y = rand() % 50;
	result_2 = terminarviaje_1(&terminarviaje_1_arg, clnt);
	if (result_2 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("Terminando viaje. Gracias por tu preferencia de parte del equipo de MicroUber :D\n\n");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	requests_1 (host);
exit (0);
}
